DimeTimetrackerBundle:
    resource: "@DimeTimetrackerBundle/Resources/config/routing.yml"

DimeTimetrackerFrontendBundle:
    resource: "@DimeTimetrackerFrontendBundle/Resources/config/routing.yml"

DimeInvoiceBundle:
    resource: "@DimeInvoiceBundle/Resources/config/routing.yml"
    prefix:   /

