dime_frontend:
    resource: "@DimeFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

dime_api:
    resource: "@DimeApiBundle/Controller/"
    type:     annotation
    prefix:   /

