DimeTimetrackerFrontendBundle:
    resource: "@DimeTimetrackerFrontendBundle/Resources/config/routing.yml"

DimeTimetrackerBundle:
    type:     rest
    resource: "@DimeTimetrackerBundle/Resources/config/routing.yml"
    prefix:   /api
    defaults: { _format: json }

DimeInvoiceBundle:
    resource: "@DimeInvoiceBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
DimeGanttChartBundle:    
    resource: "@DimeGanttChartBundle/Resources/config/routing.yml"
    prefix:   /  

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
